CREATE TABLE `kalendar_spolky` (
	`id` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
	`jmeno` varchar(100) COLLATE utf8_czech_ci DEFAULT NULL COMMENT 'název',
	`brand` varchar(100) COLLATE utf8_czech_ci DEFAULT NULL,
	`adresa` text COLLATE utf8_czech_ci,
	`description` varchar(250) COLLATE utf8_czech_ci DEFAULT NULL,
	`postOfficeBoxNumber` varchar(32) COLLATE utf8_czech_ci DEFAULT NULL,
	`streetAddress` varchar(250) COLLATE utf8_czech_ci DEFAULT NULL,
	`postalCode` varchar(32) COLLATE utf8_czech_ci DEFAULT NULL,
	`addressLocality` varchar(250) COLLATE utf8_czech_ci DEFAULT NULL,
	`addressCountry` varchar(32) COLLATE utf8_czech_ci DEFAULT NULL,
	`telefon` varchar(44) COLLATE utf8_czech_ci DEFAULT NULL,
	`fax` varchar(32) COLLATE utf8_czech_ci DEFAULT NULL,
	`email` varchar(64) COLLATE utf8_czech_ci DEFAULT NULL,
	`www` varchar(100) COLLATE utf8_czech_ci DEFAULT NULL,
	`FB` varchar(100) COLLATE utf8_czech_ci DEFAULT NULL COMMENT 'odkaz na stránku nebo skupinu',
	`dopravce` varchar(6) COLLATE utf8_czech_ci DEFAULT NULL,
	`taxId` varchar(32) COLLATE utf8_czech_ci DEFAULT NULL,
	`foundingDate` date DEFAULT NULL COMMENT 'den založení',
	`dissolutionDate` date DEFAULT NULL COMMENT 'den zrušení',
	`typ` smallint(5) NOT NULL DEFAULT '0',
	`seo_url` varchar(250) COLLATE utf8_czech_ci DEFAULT NULL,
	`active` tinyint(1) NOT NULL DEFAULT '1',
	`modified` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`),
	KEY `seo_url` (`seo_url`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_czech_ci;
